### PR TITLE
feat(models): set of functions to manage model versions!

### LINKED ISSUE #55: [Hacktoberfest] A set of functions to manage model versions
## Task

Implement a set of functions to manage model versions in JavaScript SDK ([based on Python SDK](https://docs.mindsdb.com/sdks/python/manage-model-versions)).

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

### PR DESCRIPTION
**Pull request by ArnavK-09**
+formatted
resolves #55

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@quest-bot loot #55

**Comment by ArnavK-09** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ArnavK-09** [comment]
@ZoranPandovski any fix for cla workflow?

**Comment by chandrevdw31** [comment]
@ArnavK-09 can you merge main branch in the pr please.

**Comment by ArnavK-09** [comment]
> @ArnavK-09 can you merge main branch in the pr please.

this branch is already updated to main :/
or you saying something else? sorry

image

**Comment by ArnavK-09** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ArnavK-09** [comment]
recheck

**Review by setohe0909 — APPROVED** [review]

**Pull request merged**
