### PR TITLE
Implemented method to create project

### LINKED ISSUE #50: [Hacktoberfest] A function to create a project
## Task

Implement a function to create a project in JavaScript SDK.

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

### PR DESCRIPTION
**Pull request by md-abid-hussain**
closes #50

### CODE REVIEW

**Comment by md-abid-hussain** [comment]
@quest-bot loot #50

**Comment by chandrevdw31** [comment]
@md-abid-hussain can you merge main branch in the pr please.

**Comment by md-abid-hussain** [comment]
Is it good now?

**Comment by md-abid-hussain** [comment]
@chandrevdw31 can you please review it.

**Review by mpacheco12 — APPROVED** [review]

**Pull request merged**
