### PR TITLE
upload file

### LINKED ISSUE #81: [Hacktoberfest] A function to upload a file
## Task

Implement a function to upload a file in JavaScript SDK.

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

### PR DESCRIPTION
**Pull request by Better-Boy**
Fixes #81

### CODE REVIEW

**Comment by Better-Boy** [comment]
@setohe0909 can you please review this PR?

**Review by mpacheco12 — APPROVED** [review]

**Review by mpacheco12 — APPROVED** [review]

**Comment by mpacheco12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mpacheco12** [comment]
recheck

**Comment by mpacheco12** [comment]
recheck

**Pull request merged**
