### PR TITLE
Added configure function

### PR DESCRIPTION
**Pull request by Niharika0104**
**Closes - #47**
Added configure() function.This function will create the ml engine.

### CODE REVIEW

**Comment by Niharika0104** [comment]
@quest-bot loot https://github.com/mindsdb/mindsdb-js-sdk/issues/47

**Comment by chandrevdw31** [comment]
@Niharika0104 can you merge main branch in the pr please.

**Comment by Niharika0104** [comment]
@chandrevdw31 Done

**Comment by Niharika0104** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Niharika0104** [comment]
recheck

**Review by mpacheco12 — APPROVED** [review]

**Comment by Niharika0104** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mpacheco12** [comment]
recheck

**Pull request merged**
