### PR TITLE
[Hacktoberfest] Job functionality

### PR DESCRIPTION
**Pull request by HahaBill**
# Job functionality

Developers can now:

1. Create a job (issue #84)
2. Delete a job (issue #85)

#### 1. Create a job 

```javascript
  const jobName = '<YOUR JOB NAME>';
  const project = '<YOUR PROJECT NAME>';
  const job = MindsDB.Jobs.createJob(jobName, project);

  job.addQuery('INSERT INTO integration_name.table_name(SELECT * from integration_name_two.table_name_two)');
  job.setEvery('1 MINUTE')
  await job.create();

```

https://github.com/user-attachments/assets/a366e5cd-97b3-41dc-9a8b-86b3f5576b74

#### 2. Delete a job 

```javascript
  const jobName = 'test_deleting_job';
  const project = 'hahabill';
  const job = MindsDB.Jobs.create(jobName, project);

  job.addQuery('INSERT INTO clickhouse_conn.mindsdb_create_job (SELECT * from clickhouse_conn.minds_insert_via_job)');
  job.setEvery('1 MINUTE')
  await job.createJob();

  await MindsDB.Jobs.dropJob(jobName, project);
```

https://github.com/user-attachments/assets/25e883a5-29f5-45a8-89e2-9b763cfcb844

### CODE REVIEW

**Comment by HahaBill** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by HahaBill** [comment]
recheck

**Comment by HahaBill** [comment]
I will explain the implementation more in detail and add sorts of documentation soon!

**Comment by chandrevdw31** [comment]
@HahaBill can you merge main branch in the pr please.

**Review by setohe0909 — APPROVED** [review]

**Pull request merged**
